spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 199986
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
    mode: HTML5
    servlet:
      content-type: text/html
    suffix: .html
    encoding: UTF-8
logging:
  level:
    root: info
    com.hyp: debug
  file:
    path: logs/blog-dev.log

